matches:
  - trigger: "/now " 
    replace: "{today}"
    vars:
    - name: today
      type: date
      params:
        format: "%m/%d/%Y"

  - trigger: "/comdata "
    replace: "#507

              #511

              #512

              #514

              $total = 
              $fees = 

              $total - $fees"